export const fetchEquipmentPool = () => {
  return [
    {
      "uid": "600006",
      "name": "Arena Shield",
      "abilities": [],
      "aspd": 0,
      "atk": 0,
      "cri": 0,
      "criDamage": 0,
      "def": 40,
      "flee": 0,
      "hit": 0,
      "hpMAX":0,
      "spMAX":0,
      "mAtk":0,
      "mDef":20,
      "speed":0,
      "price":300,
      "slot":3,
      "level_required":0,
      "description": "Arena Shield",
      "icon": "600006",
      "type": "armor",
      "jobRequired": {
      "Acolyte" : true,
      "Archer" : true,
      "Lancer" : true,
      "Mage" : true,
      "Swordman" : true,
      }
      ,"range" : 0
    },
    {
      "uid": "600007",
      "name": "Arena Helmet",
      "abilities": [],
      "aspd": 0,
      "atk": 0,
      "cri": 0,
      "criDamage": 0,
      "def": 30,
      "flee": 0,
      "level_required":0,
      "hit": 0,
      "hpMAX":0,
      "spMAX":0,
      "mAtk":0,
      "mDef":30,
      "speed":0,
      "price":300,
      "slot":2,
      "description": "Arena Helmet",
      "icon": "600007",
      "type": "armor",
      "jobRequired": {
      "Acolyte" : true,
      "Archer" : true,
      "Lancer" : true,
      "Mage" : true,
      "Swordman" : true,
      },"range" : 0
    },
    {
      "uid": "600008",
      "name": "Arena Boot",
      "abilities": [],
      "aspd": 0,
      "atk": 0,
      "cri": 0,
      "criDamage": 0,
      "def": 10,
      "flee": 0,
      "level_required":0,
      "hit": 0,
      "hpMAX":0,
      "spMAX":0,
      "mAtk":0,
      "mDef":5,
      "speed":1,
      "price":300,
      "slot":4,
      "description": "Arena Boot",
      "icon": "600008",
      "type": "armor",
      "jobRequired": {
      "Acolyte" : true,
      "Archer" : true,
      "Lancer" : true,
      "Mage" : true,
      "Swordman" : true,
      },"range" : 0
    },
    {
      "uid": "600009",
      "name": "Arena Armor",
      "abilities": [],
      "aspd": 0,
      "atk": 0,
      "cri": 0,
      "criDamage": 0,
      "def": 50,
      "flee": 0,
      "level_required":0,
      "hit": 0,
      "hpMAX":0,
      "spMAX":0,
      "mAtk":0,
      "mDef":50,
      "speed":0,
      "price":300,
      "slot":1,
      "description": "Arena Armor",
      "icon": "600009",
      "type": "armor",
      "jobRequired": {
      "Acolyte" : true,
      "Archer" : true,
      "Lancer" : true,
      "Mage" : true,
      "Swordman" : true,
      },"range" : 0
    },
    {
      "uid": "610001",
      "name": "Arena Sword",
      "abilities": [],
      "aspd": 1,
      "atk": 80,
      "cri": 1,
      "criDamage": 13,
      "def": 0,
      "flee": 0,
      "level_required":0,
      "hit": 0,
      "hpMAX":0,
      "spMAX":0,
      "mAtk":0,
      "mDef":0,
      "speed":0,
      "price":300,
      "slot":0,
      "description": "Arena Sword",
      "icon": "610001",
      "type": "weapon",
      "jobRequired": {
        "Acolyte" : false,
        "Archer" : false,
        "Lancer" : false,
        "Mage" : false,
        "Swordman" : true,
      },"range" : 0
    },
    {
      "uid": "610002",
      "name": "Arena Spear",
      "abilities": [],
      "aspd": 0.9,
      "atk": 100,
      "cri": 1,
      "criDamage": 0,
      "def": 0,
      "flee": 0,
      "level_required":0,
      "hit": 0,
      "hpMAX":0,
      "spMAX":0,
      "mAtk":0,
      "mDef":0,
      "speed":0,
      "price":300,
      "slot":0,
      "description": "Arena Spear",
      "icon": "610002",
      "type": "weapon",
      "jobRequired": {
        "Acolyte" : false,
        "Archer" : false,
        "Lancer" : true,
        "Mage" : false,
        "Swordman" : false,
      },"range" : 0
    },
    {
      "uid": "610003",
      "name": "Book of Arena",
      "abilities": [],
      "aspd": 0.9,
      "atk": 30,
      "cri": 1,
      "criDamage": 0,
      "def": 0,
      "flee": 0,
      "level_required":0,
      "hit": 0,
      "hpMAX":0,
      "spMAX":0,
      "mAtk":70,
      "mDef":0,
      "speed":0,
      "price":300,
      "slot":0,
      "description": "Book of Arena",
      "icon": "610003",
      "type": "weapon",
      "jobRequired": {
        "Acolyte" : true,
        "Archer" : false,
        "Lancer" : false,
        "Mage" : false,
        "Swordman" : false,
      },"range" : 0
    },
    {
      "uid": "610004",
      "name": "Arena Staff",
      "abilities": [],
      "aspd": 0.7,
      "atk": 0,
      "cri": 1,
      "criDamage": 0,
      "def": 0,
      "flee": 0,
      "level_required":0,
      "hit": 0,
      "hpMAX":0,
      "spMAX":0,
      "mAtk":100,
      "mDef":0,
      "speed":0,
      "price":300,
      "slot":0,
      "description": "Arena Staff",
      "icon": "610004",
      "type": "weapon",
      "jobRequired": {
        "Acolyte" : false,
        "Archer" : false,
        "Lancer" : false,
        "Mage" : true,
        "Swordman" : false,
      },"range" : 0
    },
      {
      "uid": "610005",
      "name": "Arena Bow",
      "abilities": [],
      "aspd": 0.8,
      "atk": 70,
      "cri": 0.5,
      "criDamage": 0,
      "def": 0,
      "flee": 0,
      "level_required":0,
      "hit": 0,
      "hpMAX":0,
      "spMAX":0,
      "mAtk":100,
      "mDef":0,
      "speed":0,
      "price":300,
      "slot":0,
      "description": "610005",
      "icon": "Arena Bow",
      "type": "weapon",
      "jobRequired": {
        "Acolyte" : false,
        "Archer" : true,
        "Lancer" : false,
        "Mage" : false,
        "Swordman" : false,
      },"range" : 0
    },
  ]
}
