export const fetchMonsterPool = () => {
  return [
    {
      "uid": "100003",
      "name": "Snake",
      "aspd": 1,
      "atk": 100,
      "cri": 10,
      "def": 30,
      "exp": 10,
      "free": 10,
      "hit": 50,
      "hp": 600,
      "level": 3,
      "mAtk": 10,
      "mDef": 5,
      "range": 50,
      "speed": 2,
      "type" : "dungeon",
      "vision" : 5
    },
    {
      "uid": "100004",
      "name": "Bird",
      "aspd": 1,
      "atk": 80,
      "cri": 10,
      "def": 50,
      "exp": 10,
      "free": 30,
      "hit": 60,
      "hp": 800,
      "level": 3,
      "mAtk": 5,
      "mDef": 15,
      "range": 100,
      "speed": 3,
      "type" : "dungeon",
      "vision" : 10
    },
    {
      "uid": "100005",
      "name": "Bear",
      "aspd": 1,
      "atk": 80,
      "cri": 10,
      "def": 50,
      "exp": 12,
      "free": 1,
      "hit": 60,
      "hp": 1500,
      "level": 3,
      "mAtk": 5,
      "mDef": 20,
      "range": 50,
      "speed": 1,
      "type" : "dungeon",
      "vision" : 4
    },
    {
      "uid": "100006",
      "name": "Orc",
      "aspd": 1,
      "atk": 140,
      "cri": 10,
      "def": 30,
      "exp": 15,
      "free": 20,
      "hit": 70,
      "hp": 800,
      "level": 5,
      "mAtk": 10,
      "mDef": 10,
      "range": 50,
      "speed": 1.4,
      "type" : "dungeon",
      "vision" : 8
    },
    {
      "uid": "110001",
      "name": "Slime",
      "aspd": 1,
      "atk": 180,
      "cri": 15,
      "def": 35,
      "exp": 30,
      "free": 25,
      "hit": 70,
      "hp": 10000,
      "level": 10,
      "mAtk": 15,
      "mDef": 20,
      "range": 80,
      "speed": 3,
      "type" : "dungeon",
      "vision" : 8
    },
    {
      "uid": "chest001",
      "name": "chest001",
      "aspd": 0,
      "atk": 0,
      "cri": 0,
      "def": 0,
      "exp": 0,
      "free": 0,
      "hit": 0,
      "hp": 200,
      "level": 0,
      "mAtk": 0,
      "mDef": 0,
      "range": 0,
      "speed": 0,
      "type" : "treasure",
      "vision" : 0
    }
]
}
